### ISSUE TITLE
Testing SDL2

### ISSUE THREAD

**Issue by david-i** [TheSaturdayThing/Arcade#3]
A fresh install of Raspberry Pi OS "bookworm" comes with pre-compiled versions of SDL2 , image, mixer, and tff.
Also the default display manager is set to "**wayland**" rather than "**X11**".

Are these default libraries and settings functional?
Is there a simple program that can be run as an acceptance test before we use the software as the basis for compiling the Pong and PacMan games?

**Comment by david-i** [comment]
A possible test:
https://gist.github.com/miguelmartin75/6946310

**Comment by LucaFeggi** [comment]
In the srd directiory I uploaded a folder for testing with Test.cpp, CMakeLists.txt to compile it, and .dll files to make it work. It initialize all the 4 libraries (SDL, TTF, IMG, MIX) and renders a black window (press esc key to quit or click the red X icon with the mouse).

**Comment by david-i** [comment]
Thanks,
I cloned the repo from github onto my Rpi, went into the Test folder and made a build directory.
I then ran cmake and make to create the "Test" executable.

I was able to run the Test program from either a terminal window ot from GUI by double clicking the program, I got the black box and was able to close it from the X icon (which was black, not red.

Hiow were the DLL files created for this test?

**Comment by david-i** [comment]
I tried compiling Pong and got the no joystick/seg fault error
(this was connecting over VNC; I will need to try at the console next).

![image](https://github.com/TheSaturdayThing/Arcade/assets/4332426/c6193f64-fa3f-4869-868f-2074f38cb377)

**Comment by david-i** [comment]
I went into Arcade/src/PacMan and created a build dir.
In that dir I ran cmake and make.

To resolve the path to the texture path, I went up a level and make a symlink pointing to the executable in the build dir.

from a VNC terminal, I ran the PacMan program and got this. As expected?

![image](https://github.com/TheSaturdayThing/Arcade/assets/4332426/ebe22f05-b4e9-40a6-98c0-62a4f3c983b3)

**Comment by david-i** [comment]
May need to review the Cmake commands;
I think they added the path to /usrl/local to find re-compiled packages, but now those things are in their default areas; e.g.

`/usr/bin/sdl2-config`

**Comment by david-i** [comment]
Wiki steps here:
https://github.com/TheSaturdayThing/Arcade/wiki/Compiling-games-with-SDL2

**Comment by LucaFeggi** [comment]
> Thanks, I cloned the repo from github onto my Rpi, went into the Test folder and made a build directory. I then ran **cmake** and **make** to create the "Test" executable.
> 
> I was able to run the Test program from either a terminal window or from GUI by double clicking the program, I got the black window and was able to close it both with 'ESC' and from the X icon (which was black, not red.
> 
> How were the DLL files created for this test?
> 
> ![image](https://private-user-images.githubusercontent.com/4332426/301610489-3d6c3723-ae0c-4cc4-85e7-0d70bd260d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQ4NDcsIm5iZiI6MTcwNjg4NDU0NywicGF0aCI6Ii80MzMyNDI2LzMwMTYxMDQ4OS0zZDZjMzcyMy1hZTBjLTRjYzQtODVlNy0wZDcwYmQyNjBkMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTQzNTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZjMWM5MmI1NTU0MTgzOTIxMjZhOTVhYmI5N2RmNWYyNzIxYjU0YThmOTczOTdmOGExMzMzMDcwNjFjMzIzZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rHVNEw7bHCoJcHf9SdnXzOYjKEgtIqFMk6hDfUqpLuE)

I didn't create the .dll, I just copied them. They are needed to run the executable (on windows). They have to be in the same directory of the .exe file. I don't know if they are required on the RasPi environment.

**Comment by LucaFeggi** [comment]
I followed all the steps and managed to compile and run all the programs on my RasPi! The sounds are working. Tomorrow I will try to connect joysticks and buttons and see what happens. Thank you.

**Comment by LucaFeggi** [comment]
Joystick and buttons connected, everything works fine. Thank you for the support.
