### ISSUE TITLE
Joystick/button connection code?

### ISSUE THREAD

**Issue by david-i** [TheSaturdayThing/Arcade#5]
- How do the joystick and buttons connect to the Raspberry Pi for PacMan?
- Can Pong use keyboard inputs (WASD keys) when there is no joystick, similar to how PacMan works?

**Comment by LucaFeggi** [comment]
I added the possibility to move the Pong paddles with the keyboard.
Left Paddle up -> Q
Left Paddle Down -> A
Right Paddle up -> E
Right Paddle Down -> D

**Comment by david-i** [comment]
ok; i didn't realize the controls were connected over USB; for some reason I thought an Arduino was reading the buttons and sending info via some method to the RPi.

BTW, I took the new pong code and am able to move the paddles via the keyboard. thanks
Is there documentation someplace on how to restart a new game?

**Comment by LucaFeggi** [comment]
I did not implement the possibility to restart the match when I first coded Pong. The same for PacMan. However I'm currently  making a new version of PacMan that will have that possibility; as soon as I finish it, I will upload the code in the Arcade/src directory.
